### ISSUE TITLE
[Help needed] How to set client/server type when uploading to e.g. curse?

### ISSUE THREAD

**Issue by jh-devv** [Kir-Antipov/mc-publish#92] opened 2023-09-30 08:21 UTC

**Comment by Kir-Antipov** [comment] 2023-10-01 01:20
This is a duplicate of #64, so, please, refer to that issue instead.

TL;DR: the latest `mc-publish` version was published before CurseForge added `environment`s, therefore there's no such functionality built-in at the moment, but it's scheduled.

**Closed by Kir-Antipov** 2023-10-01 01:20 UTC
