### ISSUE TITLE
Error messages need improving

### ISSUE THREAD

**Issue by NoComment1105** [Kir-Antipov/mc-publish#3] opened 2021-12-08 14:43 UTC
In my development of an action I was receiving and error that simply said `Error: Not Found`. I have managed to deduce from further development that I made on the action, that this error is related to the GitHub token being incorrect. But this took me quite a lot of time to figure out, which was very frustrating. 

I would like to request that some of your error messages are looked over again and improved, for easier debugging of action issues

**Comment by Kir-Antipov** [comment] 2021-12-08 14:56
These are the only entries of "Not found" in the entire project:

 - `throw new Error("Changelog file was not found");`
 - `throw new Error('Specified files ... were not found');`

I think, it has something to do with the official `octokit` package

**Comment by NoComment1105** [comment] 2021-12-08 15:12
Odd :/

**Comment by Kir-Antipov** [comment] 2021-12-10 14:26
I absolutely agree that errors should explicitly describe the problem (it's especially true for GitHub Actions, because it's one hell of debugging them). But the problem is not related to the action itself, I tried to make my errors as explicit as possible, therefore the issue is most likely caused by one of the underlying npm packages. I don't want to fall back on heuristics in order to replace one error message with another one, so this won't be fixed until the package that throws this error will reconsider its life choices. Closing this one at the moment

**Closed** 2021-12-10 14:26 UTC
Labels: wontfix
