### ISSUE TITLE
Node.js 12 is deprecated 

### ISSUE THREAD

**Issue by cech12** [Kir-Antipov/mc-publish#44] opened 2022-12-30 17:25 UTC
When I run your action, I get this warning:

   Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Kir-Antipov/mc-publish@v3.2

Thanks for your help! :)

**Comment by Kir-Antipov** [comment] 2023-01-02 14:16
Don't worry, I'm working on it

This is a duplicate of #39, therefore I'm gonna close this one. If you have any questions on the progress, feel free to ask them there

**Closed by Kir-Antipov** 2023-01-02 14:16 UTC
Labels: duplicate
