### ISSUE TITLE
Minecraft version detection for fabric mods is inaccurate.

### ISSUE THREAD

**Issue by mineblock11** [Kir-Antipov/mc-publish#57] opened 2023-04-03 17:20 UTC
My `fabric.mod.json` specifies minecraft version as `=1.19.3`, which in semver standards means it requires specifically minecraft 1.19.3

For some reason, mc-publish is treating this as 1.19.3+, all versions above or equal to 1.19.3

**Comment by Kir-Antipov** [comment] 2023-04-04 12:32
At the moment, this is by design. From the beginning of this project, I needed a simple method to unify Forge version ranges and Fabric version ranges. The solution I devised was to extract the first version from the version string and use it as a reference point to recreate the range a user desires. By default, the action assumes that you specified something like `>=version` (or `[version, )`). In your case you need to give a hint to mc-publish with the help of [`version-resolver`](https://github.com/Kir-Antipov/mc-publish#version-resolver):

```yaml
version-resolver: exact
```

You don't need to tell me that this is a terrible design; I am aware of that. I needed a quick workaround for the time being, and it has managed to survive until this very day somehow.

![Hack vs Well-thought solution](https://user-images.githubusercontent.com/40232067/229789710-8076ba81-3e1b-4b53-a11d-f608f7c78184.png)

This behavior will be changed as a part of [#25](https://github.com/Kir-Antipov/mc-publish/issues/25#issuecomment-1239794771). The new one should match your expectations perfectly.

I am going to close this issue (there are already three on this topic), but you can track the progress and leave your thoughts or suggestions on the linked one.

**Closed by Kir-Antipov** 2023-04-04 12:32 UTC
